// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aPZu6epBt5EaEYRgMF1d6z
// Component: -QdVHAhp0j
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_code_component_examples.module.css"; // plasmic-import: aPZu6epBt5EaEYRgMF1d6z/projectcss
import * as sty from "./PlasmicSectionHeading.module.css"; // plasmic-import: -QdVHAhp0j/css

export type PlasmicSectionHeading__VariantMembers = {};

export type PlasmicSectionHeading__VariantsArgs = {};
type VariantPropType = keyof PlasmicSectionHeading__VariantsArgs;
export const PlasmicSectionHeading__VariantProps = new Array<VariantPropType>();

export type PlasmicSectionHeading__ArgsType = {};
type ArgPropType = keyof PlasmicSectionHeading__ArgsType;
export const PlasmicSectionHeading__ArgProps = new Array<ArgPropType>();

export type PlasmicSectionHeading__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultSectionHeadingProps {
  className?: string;
}

function PlasmicSectionHeading__RenderFunc(props: {
  variants: PlasmicSectionHeading__VariantsArgs;
  args: PlasmicSectionHeading__ArgsType;
  overrides: PlasmicSectionHeading__OverridesType;
  dataFetches?: PlasmicSectionHeading__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {false ? (
        <div className={classNames(defaultcss.all, sty.box__f50Rd)} />
      ) : null}

      <div
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.box___9Rn6I
        )}
      >
        {"Use off-the-shelf components."}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSectionHeading__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSectionHeading__VariantsArgs;
    args?: PlasmicSectionHeading__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicSectionHeading__Fetches;
  } & Omit<PlasmicSectionHeading__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSectionHeading__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSectionHeading__ArgProps,
      internalVariantPropNames: PlasmicSectionHeading__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicSectionHeading__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionHeading";
  } else {
    func.displayName = `PlasmicSectionHeading.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionHeading = Object.assign(
  // Top-level PlasmicSectionHeading renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSectionHeading
    internalVariantProps: PlasmicSectionHeading__VariantProps,
    internalArgProps: PlasmicSectionHeading__ArgProps
  }
);

export default PlasmicSectionHeading;
/* prettier-ignore-end */
