// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: 4hNukt77tQq
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: vtgKf8zu4R/component
import Footer from "../../Footer"; // plasmic-import: 9R5YynM9KVp/component

import { ThemeContext, ThemeValue } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: 9MzawQbD5r/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicAbout.module.css"; // plasmic-import: 4hNukt77tQq/css

import Icon37Icon from "./icons/PlasmicIcon__Icon37"; // plasmic-import: SCO2nowOyF/icon

export type PlasmicAbout__VariantMembers = {};

export type PlasmicAbout__VariantsArgs = {};
type VariantPropType = keyof PlasmicAbout__VariantsArgs;
export const PlasmicAbout__VariantProps = new Array<VariantPropType>();

export type PlasmicAbout__ArgsType = {};
type ArgPropType = keyof PlasmicAbout__ArgsType;
export const PlasmicAbout__ArgProps = new Array<ArgPropType>();

export type PlasmicAbout__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  body?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultAboutProps {
  dataFetches: PlasmicAbout__Fetches;
}

function PlasmicAbout__RenderFunc(props: {
  variants: PlasmicAbout__VariantsArgs;
  args: PlasmicAbout__ArgsType;
  overrides: PlasmicAbout__OverridesType;
  dataFetches?: PlasmicAbout__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    theme: React.useContext(ThemeContext)
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"About Plasmic"}</title>
        <meta key="og:title" property="og:title" content={"About Plasmic"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Plasmic's mission is to democratize software creation and empower everyone to bring their ideas to life. We are proudly funded by NEA."
          }
        />
        <meta
          key="og:image"
          property="og:image"
          content={
            "/plasmic/plasmic_kit_website_components/images/websiteHeroImageTinypng.png"
          }
        />
      </Head>

      <style global jsx>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root,
            {
              [sty.root__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            }
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header, {
              [sty.header__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })}
          />

          <p.Stack
            as={"div"}
            data-plasmic-name={"body"}
            data-plasmic-override={overrides.body}
            hasGap={true}
            className={classNames(defaultcss.all, sty.body, {
              [sty.body__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })}
          >
            <div className={classNames(defaultcss.all, sty.box__mdhtS)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__ptIR)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___6BJoa
                  )}
                >
                  {"Mission"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___66KzZ
                  )}
                >
                  {
                    "Democratize software creation and empower everyone to bring their ideas to life."
                  }
                </div>
              </p.Stack>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__tu3Lf)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__bN4RS,
                  {
                    [sty.box__global_theme_dark__bN4RSh5AZc]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  }
                )}
              >
                {"Team"}
              </div>

              <div className={classNames(defaultcss.all, sty.box__u50Wx)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__gkt2T
                  )}
                >
                  {
                    "We are a merry band of engineers, designers, and dreamers from Google, Microsoft, Facebook, and Dropbox."
                  }
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box__sssAh)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__chUs6
                  )}
                >
                  {
                    "We're hiring more engineers and designers. If Plasmic's mission resonates with you, say hello!"
                  }
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box___4N0Vf)}>
                <p.PlasmicLink
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.link__pHt34
                  )}
                  component={Link}
                  href={"mailto:hiring+about@plasmic.app" as const}
                  platform={"nextjs"}
                >
                  {"hiring@plasmic.app"}
                </p.PlasmicLink>
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__cvmx8)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__p2S1,
                  {
                    [sty.box__global_theme_dark__p2S1H5AZc]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  }
                )}
              >
                {"Investors"}
              </div>

              <div className={classNames(defaultcss.all, sty.box__wbGpJ)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___70Bng
                  )}
                >
                  {
                    "We are proudly backed by NEA, Tiny Capital, Designer Fund, Prime Set, #Angels, Arrive, and esteemed founders and investors."
                  }
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box__k6Bsq)}>
                <Icon37Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(defaultcss.all, sty.svg)}
                  role={"img"}
                />
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__m2L9I)}
              >
                <p.PlasmicLink
                  className={classNames(defaultcss.all, sty.link__mr1Qa)}
                  component={Link}
                  href={"https://www.tinycapital.com/" as const}
                  platform={"nextjs"}
                  title={"Tiny Capital" as const}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__cg0Uf)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image63.png"
                    }
                  />
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(defaultcss.all, sty.link__kOhb2)}
                  component={Link}
                  href={"https://www.designerfund.com/" as const}
                  platform={"nextjs"}
                >
                  <img
                    alt={"Designer Fund" as const}
                    className={classNames(defaultcss.img, sty.img___1Qt78)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image65.png"
                    }
                  />
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(defaultcss.all, sty.link__dlMd)}
                  component={Link}
                  href={"https://www.primeset.com/" as const}
                  platform={"nextjs"}
                >
                  <img
                    alt={"Prime Set" as const}
                    className={classNames(defaultcss.img, sty.img__kCe9C)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image61.png"
                    }
                  />
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(defaultcss.all, sty.link___5BHbQ)}
                  component={Link}
                  href={"https://hashtagangels.com/" as const}
                  platform={"nextjs"}
                >
                  <img
                    alt={"#Angels" as const}
                    className={classNames(defaultcss.img, sty.img__zHyPm)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image60.png"
                    }
                  />
                </p.PlasmicLink>

                <p.PlasmicLink
                  className={classNames(defaultcss.all, sty.link___3Qn4B)}
                  component={Link}
                  href={"https://www.arrive.co/" as const}
                  platform={"nextjs"}
                >
                  <img
                    alt={"Arrive" as const}
                    className={classNames(defaultcss.img, sty.img__uqcjV)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image62.png"
                    }
                  />
                </p.PlasmicLink>
              </p.Stack>

              {false ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__pg9Be)}
                >
                  <div className={classNames(defaultcss.all, sty.box___8HB1M)}>
                    <img
                      alt={""}
                      className={classNames(defaultcss.img, sty.img__crrEl)}
                      role={"img"}
                      src={
                        "/plasmic/plasmic_kit_website_components/images/image63.png"
                      }
                    />
                  </div>

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__d6XY)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image66.png"
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ynnW0)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image67.png"
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__r1Wy5)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image68.png"
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3S8Ek)}
                    role={"img"}
                    src={
                      "/plasmic/plasmic_kit_website_components/images/image62.png"
                    }
                  />
                </p.Stack>
              ) : null}
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer, {
              [sty.footer__global_theme_dark]: hasVariant(
                globalVariants,
                "theme",
                "dark"
              )
            })}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "body", "svg", "footer"],
  header: ["header"],
  body: ["body", "svg"],
  svg: ["svg"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  body: "div";
  svg: "svg";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAbout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAbout__VariantsArgs;
    args?: PlasmicAbout__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAbout__Fetches;
  } & Omit<PlasmicAbout__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAbout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAbout__ArgProps,
      internalVariantPropNames: PlasmicAbout__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAbout";
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`;
  }
  return func;
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    body: makeNodeComponent("body"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps
  }
);

export default PlasmicAbout;
/* prettier-ignore-end */
