// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: jlcB8VeL6C_
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import CommonLandingPage from "../../CommonLandingPage"; // plasmic-import: HzhMCW_ztWQ/component
import IntegrateAnywhereSection from "../../IntegrateAnywhereSection"; // plasmic-import: dxALvsaixcT/component
import ValuePropListItem from "../../ValuePropListItem"; // plasmic-import: lJppbKgSOw/component
import GraphicIcon from "../../GraphicIcon"; // plasmic-import: TcXkT68Mp6/component
import Divider from "../../Divider"; // plasmic-import: SQHouqji3_/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicSiteBuilder.module.css"; // plasmic-import: jlcB8VeL6C_/css

import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: d8TOpAp1CP/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: YhhYiXTtXT/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: 5amV9exkN9/icon

export type PlasmicSiteBuilder__VariantMembers = {};

export type PlasmicSiteBuilder__VariantsArgs = {};
type VariantPropType = keyof PlasmicSiteBuilder__VariantsArgs;
export const PlasmicSiteBuilder__VariantProps = new Array<VariantPropType>();

export type PlasmicSiteBuilder__ArgsType = {};
type ArgPropType = keyof PlasmicSiteBuilder__ArgsType;
export const PlasmicSiteBuilder__ArgProps = new Array<ArgPropType>();

export type PlasmicSiteBuilder__OverridesType = {
  root?: p.Flex<"div">;
  commonLandingPage?: p.Flex<typeof CommonLandingPage>;
  box?: p.Flex<"div">;
};

export interface DefaultSiteBuilderProps {
  dataFetches: PlasmicSiteBuilder__Fetches;
}

function PlasmicSiteBuilder__RenderFunc(props: {
  variants: PlasmicSiteBuilder__VariantsArgs;
  args: PlasmicSiteBuilder__ArgsType;
  overrides: PlasmicSiteBuilder__OverridesType;
  dataFetches?: PlasmicSiteBuilder__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">
          {"Plasmic - the website builder that never limits you"}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={"Plasmic - the website builder that never limits you"}
        />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Plasmic is a visual, no-code website builder that lets you deploy anywhere and extend with code."
          }
        />
        <meta
          key="og:image"
          property="og:image"
          content={
            "/plasmic/plasmic_kit_website_components/images/websiteHeroImageTinypng.png"
          }
        />
      </Head>

      <style global jsx>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <CommonLandingPage
            data-plasmic-name={"commonLandingPage"}
            data-plasmic-override={overrides.commonLandingPage}
            className={classNames("__wab_instance", sty.commonLandingPage)}
            slot={"The website builder that never limits you."}
            slot2={
              "Finally—a powerful, no-code WYSIWYG builder that is open-architecture, integrates with arbitrary code, never locks you in, and scales to the most complex requirements."
            }
          >
            <div
              data-plasmic-name={"box"}
              data-plasmic-override={overrides.box}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box
              )}
            >
              {"Make your site editable to the whole team."}
            </div>
          </CommonLandingPage>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "commonLandingPage", "box"],
  commonLandingPage: ["commonLandingPage", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  commonLandingPage: typeof CommonLandingPage;
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSiteBuilder__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSiteBuilder__VariantsArgs;
    args?: PlasmicSiteBuilder__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicSiteBuilder__Fetches;
  } & Omit<PlasmicSiteBuilder__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSiteBuilder__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSiteBuilder__ArgProps,
      internalVariantPropNames: PlasmicSiteBuilder__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicSiteBuilder__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSiteBuilder";
  } else {
    func.displayName = `PlasmicSiteBuilder.${nodeName}`;
  }
  return func;
}

export const PlasmicSiteBuilder = Object.assign(
  // Top-level PlasmicSiteBuilder renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    commonLandingPage: makeNodeComponent("commonLandingPage"),
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicSiteBuilder
    internalVariantProps: PlasmicSiteBuilder__VariantProps,
    internalArgProps: PlasmicSiteBuilder__ArgProps
  }
);

export default PlasmicSiteBuilder;
/* prettier-ignore-end */
