// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: CTFlDz32c2
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ButtonLink from "../../ButtonLink"; // plasmic-import: jzdXOPDUzV/component

import { ThemeContext, ThemeValue } from "./PlasmicGlobalVariant__Theme"; // plasmic-import: 9MzawQbD5r/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicHomeHero.module.css"; // plasmic-import: CTFlDz32c2/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: wTfucAc7Rr/icon

export type PlasmicHomeHero__VariantMembers = {};

export type PlasmicHomeHero__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomeHero__VariantsArgs;
export const PlasmicHomeHero__VariantProps = new Array<VariantPropType>();

export type PlasmicHomeHero__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHomeHero__ArgsType;
export const PlasmicHomeHero__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2"
);

export type PlasmicHomeHero__OverridesType = {
  root?: p.Flex<"section">;
  container?: p.Flex<"div">;
  buttonLink?: p.Flex<typeof ButtonLink>;
  svg?: p.Flex<"svg">;
  dock?: p.Flex<"div">;
};

export interface DefaultHomeHeroProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  className?: string;
}

function PlasmicHomeHero__RenderFunc(props: {
  variants: PlasmicHomeHero__VariantsArgs;
  args: PlasmicHomeHero__ArgsType;
  overrides: PlasmicHomeHero__OverridesType;
  dataFetches?: PlasmicHomeHero__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    theme: React.useContext(ThemeContext)
  });

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__global_theme_altHeadlineFont]: hasVariant(
          globalVariants,
          "theme",
          "altHeadlineFont"
        ),
        [sty.root__global_theme_dark]: hasVariant(
          globalVariants,
          "theme",
          "dark"
        )
      })}
    >
      <div
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        className={classNames(defaultcss.all, sty.container)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__f7VC5)}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__hNrIt)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__yzLd4)}
            >
              <div
                className={classNames(defaultcss.all, sty.box__nLvV6, {
                  [sty.box__global_theme_altHeadlineFont__nLvV6FQkvX]:
                    hasVariant(globalVariants, "theme", "altHeadlineFont"),
                  [sty.box__global_theme_dark__nLvV6H5AZc]: hasVariant(
                    globalVariants,
                    "theme",
                    "dark"
                  )
                })}
              >
                <div
                  className={classNames(defaultcss.all, sty.box__c30XQ, {
                    [sty.box__global_theme_altHeadlineFont__c30XQfQkvX]:
                      hasVariant(globalVariants, "theme", "altHeadlineFont"),
                    [sty.box__global_theme_dark__c30XQh5AZc]: hasVariant(
                      globalVariants,
                      "theme",
                      "dark"
                    )
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: (
                      <span>
                        <React.Fragment>
                          {"Build front-ends ⚡️ "}
                        </React.Fragment>
                        <span style={{ fontStyle: "italic" }}>{"fast"}</span>
                        <React.Fragment>
                          {".\nFor your own codebase."}
                        </React.Fragment>
                      </span>
                    ),
                    value: args.children,
                    className: classNames(sty.slotChildren, {
                      [sty.slotChildren__global_theme_altHeadlineFont]:
                        hasVariant(globalVariants, "theme", "altHeadlineFont"),
                      [sty.slotChildren__global_theme_dark]: hasVariant(
                        globalVariants,
                        "theme",
                        "dark"
                      )
                    })
                  })}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box___1C2Y)}>
                {p.renderPlasmicSlot({
                  defaultContents: (
                    <span>
                      <React.Fragment>
                        {
                          "Visually create everything from responsive pages to complex components. Integrate with any React stack, and "
                        }
                      </React.Fragment>
                      <span style={{ fontWeight: 700 }}>
                        {"empower anyone to ship"}
                      </span>
                      <React.Fragment>{"."}</React.Fragment>
                    </span>
                  ),
                  value: args.slot,
                  className: classNames(sty.slotSlot)
                })}
              </div>
            </p.Stack>

            <ButtonLink
              data-plasmic-name={"buttonLink"}
              data-plasmic-override={overrides.buttonLink}
              href={"https://plasmic.app/signup" as const}
              icon={
                <IconIcon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(defaultcss.all, sty.svg)}
                  role={"img"}
                />
              }
              label={"Try Plasmic for free"}
              type={["purpleSolid"]}
            />
          </p.Stack>
        </p.Stack>
      </div>

      <div
        className={classNames(defaultcss.all, sty.box___13297, {
          [sty.box__global_theme_dark___13297H5AZc]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          )
        })}
      >
        <div className={classNames(defaultcss.all, sty.box__znWmw)}>
          <div className={classNames(defaultcss.all, sty.box__tmEn5)}>
            {p.renderPlasmicSlot({
              defaultContents: (
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img___7VdQf)}
                  role={"img"}
                  src={
                    "/plasmic/plasmic_kit_website_components/images/websiteHeroImageTinypng.png"
                  }
                />
              ),

              value: args.slot2
            })}

            {false ? (
              <div
                data-plasmic-name={"dock"}
                data-plasmic-override={overrides.dock}
                className={classNames(defaultcss.all, sty.dock)}
              />
            ) : null}
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "container", "buttonLink", "svg", "dock"],
  container: ["container", "buttonLink", "svg"],
  buttonLink: ["buttonLink", "svg"],
  svg: ["svg"],
  dock: ["dock"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
  container: "div";
  buttonLink: typeof ButtonLink;
  svg: "svg";
  dock: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomeHero__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomeHero__VariantsArgs;
    args?: PlasmicHomeHero__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomeHero__Fetches;
  } & Omit<PlasmicHomeHero__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomeHero__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomeHero__ArgProps,
      internalVariantPropNames: PlasmicHomeHero__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomeHero__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomeHero";
  } else {
    func.displayName = `PlasmicHomeHero.${nodeName}`;
  }
  return func;
}

export const PlasmicHomeHero = Object.assign(
  // Top-level PlasmicHomeHero renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    buttonLink: makeNodeComponent("buttonLink"),
    svg: makeNodeComponent("svg"),
    dock: makeNodeComponent("dock"),

    // Metadata about props expected for PlasmicHomeHero
    internalVariantProps: PlasmicHomeHero__VariantProps,
    internalArgProps: PlasmicHomeHero__ArgProps
  }
);

export default PlasmicHomeHero;
/* prettier-ignore-end */
